
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author floow
 */
public class Semaforo1 extends javax.swing.JFrame {

    /**
     * Creates new form Semaforo1
     */
    public Semaforo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rojo = new javax.swing.JLabel();
        Amarillo = new javax.swing.JLabel();
        Verde = new javax.swing.JLabel();
        Cambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Rojo.setText("Rojo");

        Amarillo.setText("Amarillo");

        Verde.setText("Verde");

        Cambiar.setText("CAMBIAR");
        Cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CambiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CambiarMouseExited(evt);
            }
        });
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Verde, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Amarillo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(Rojo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(Cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int ImagenNum = 0;
    
    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        // TODO add your handling code here:
        try {
        String ruta;

        if (ImagenNum == 0) {
            ruta = "C:\\Users\\floow\\Desktop\\JAVA\\SemaforoG\\src\\Archivos\\rojo.png";
            ImageIcon imagen = new ImageIcon(new ImageIcon(ruta).getImage().getScaledInstance(145, 70, Image.SCALE_DEFAULT));
             Verde.setIcon(null);
            Rojo.setIcon(imagen);
            Amarillo.setIcon(null); 
        } else if (ImagenNum == 1) {
            ruta = "C:\\Users\\floow\\Desktop\\JAVA\\SemaforoG\\src\\Archivos\\amarillo.png";
            ImageIcon imagen = new ImageIcon(new ImageIcon(ruta).getImage().getScaledInstance(145, 70, Image.SCALE_DEFAULT));
            Rojo.setIcon(null);    
            Amarillo.setIcon(imagen);
            Verde.setIcon(null);    
        } else {
            ruta = "C:\\Users\\floow\\Desktop\\JAVA\\SemaforoG\\src\\Archivos\\verde.jpeg";
            ImageIcon imagen = new ImageIcon(new ImageIcon(ruta).getImage().getScaledInstance(145, 70, Image.SCALE_DEFAULT));
            Rojo.setIcon(null);  
            Amarillo.setIcon(null);
            Verde.setIcon(imagen);
        }

        // Incrementar el índice para la próxima vez
        ImagenNum = (ImagenNum + 1) % 3;
    } catch (Exception e) {
        e.printStackTrace();
 
             
    }                    
    }//GEN-LAST:event_CambiarActionPerformed

    private void CambiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarMouseEntered
        // TODO add your handling code here:
        Cambiar.setBackground(Color.BLUE);
    }//GEN-LAST:event_CambiarMouseEntered

    private void CambiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarMouseExited
        // TODO add your handling code here:
        Cambiar.setBackground(UIManager.getColor("Cambiar"));
    }//GEN-LAST:event_CambiarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semaforo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amarillo;
    private javax.swing.JButton Cambiar;
    private javax.swing.JLabel Rojo;
    private javax.swing.JLabel Verde;
    // End of variables declaration//GEN-END:variables
}
